/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.sf.robocode.java-conventions")
}

dependencies {
    implementation(project(":robocode.api"))
    implementation(project(":robocode.roborumble"))
    implementation(project(":robocode.ui.editor"))
    implementation(project(":robocode.installer"))
    implementation(project(":robocode.content"))
}

description = "Robocode Distribution"
