rootProject.name = "robocode"
include(":robocode.api")
include(":robocode.core")
include(":robocode.repository")
include(":robocode.tests")
include(":robocode.distribution")
include(":robocode.tests.robots")
include(":robocode.samples")
include(":robocode.ui")
include(":robocode.content")
include(":robocode.host")
include(":robocode.roborumble")
include(":robocode.installer")
include(":robocode.ui.editor")
include(":robocode.sound")
include(":robocode.battle")
