//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nrobocodeui.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nrobocodeui.resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap images_body {
            get {
                object obj = ResourceManager.GetObject("images_body", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_1 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_10 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_11 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_12 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_13 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_14 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_15 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_16 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_17 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_2 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_3 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_4 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_5 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_6 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_7 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_8 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion1_9 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion1_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_1 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_10 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_11 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_12 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_13 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_14 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_15 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_16 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_17 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_18 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_19 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_2 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_20 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_21 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_22 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_23 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_24 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_25 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_26 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_27 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_28 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_29 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_3 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_30 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_31 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_32 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_33 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_34 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_35 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_36 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_37 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_38 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_39 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_4 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_40 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_41 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_42 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_43 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_44 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_45 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_46 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_47 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_48 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_49 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_5 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_50 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_51 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_52 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_53 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_54 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_55 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_56 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_57 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_58 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_59 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_59", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_6 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_60 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_61 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_62 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_63 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_63", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_64 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_65 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_66 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_67 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_68 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_69 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_7 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_70 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_71 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_8 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_explosion_explosion2_9 {
            get {
                object obj = ResourceManager.GetObject("images_explosion_explosion2_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_ground_blue_metal_blue_metal_0 {
            get {
                object obj = ResourceManager.GetObject("images_ground_blue_metal_blue_metal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_ground_blue_metal_blue_metal_1 {
            get {
                object obj = ResourceManager.GetObject("images_ground_blue_metal_blue_metal_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_ground_blue_metal_blue_metal_2 {
            get {
                object obj = ResourceManager.GetObject("images_ground_blue_metal_blue_metal_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_ground_blue_metal_blue_metal_3 {
            get {
                object obj = ResourceManager.GetObject("images_ground_blue_metal_blue_metal_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_ground_blue_metal_blue_metal_4 {
            get {
                object obj = ResourceManager.GetObject("images_ground_blue_metal_blue_metal_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_ground_explode_debris {
            get {
                object obj = ResourceManager.GetObject("images_ground_explode_debris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_radar {
            get {
                object obj = ResourceManager.GetObject("images_radar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_turret {
            get {
                object obj = ResourceManager.GetObject("images_turret", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sounds__13831_adcbicycle_22 {
            get {
                return ResourceManager.GetStream("sounds__13831_adcbicycle_22", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sounds_explode {
            get {
                return ResourceManager.GetStream("sounds_explode", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sounds_shellhit {
            get {
                return ResourceManager.GetStream("sounds_shellhit", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sounds_zap {
            get {
                return ResourceManager.GetStream("sounds_zap", resourceCulture);
            }
        }
    }
}
