#!/bin/sh
SERVICE='master'

while true
do 
if ps ax | grep -v grep | grep $SERVICE > /dev/null
then
    echo "$SERVICE service running, everything is fine"
else
    echo "$SERVICE is not running"
    ./master 
fi
done

