/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.sf.robocode.java-conventions")
}

dependencies {
    implementation(project(":robocode.samples"))
}

description = "Robocode Content"
