/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.sf.robocode.java-conventions")
}

dependencies {
    implementation(project(":robocode.api"))
    implementation(project(":robocode.core"))
    implementation(project(":robocode.battle"))
    implementation(project(":robocode.ui"))
    implementation("org.picocontainer:picocontainer:2.14.2")
}

description = "Robocode UI Robot editor"
