/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.sf.robocode.java-conventions")
}

dependencies {
    implementation(project(":robocode.api"))
    implementation(project(":robocode.tests.robots"))
    implementation("junit:junit:4.13.1")
    testImplementation(project(":robocode.core"))
    testImplementation(project(":robocode.samples"))
    testImplementation(project(":robocode.host"))
    testImplementation(project(":robocode.battle"))
    testImplementation(project(":robocode.repository"))
}

description = "Robocode Tests"
