// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package net.sf.robocode.peer;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class IRobotStatics_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return net.sf.robocode.peer.IRobotStatics_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        net.sf.robocode.peer.IRobotStatics_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __IRobotStatics extends system.Object implements net.sf.robocode.peer.IRobotStatics {
    
    protected __IRobotStatics(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isAdvancedRobot();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isTeamRobot();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isInteractiveRobot();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isPaintRobot();
}
//</generated-proxy>
