// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package net.sf.robocode.host;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class IHostedThread_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return net.sf.robocode.host.IHostedThread_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        net.sf.robocode.host.IHostedThread_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __IHostedThread extends system.Object implements net.sf.robocode.host.IHostedThread {
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/io/PrintStream;")
    public native net.sf.robocode.host.io.RobotOutputStream getOut();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void drainEnergy();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lnet/sf/robocode/host/RobotStatics;")
    public native net.sf.robocode.host.RobotStatics getStatics();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lnet/sf/robocode/host/io/RobotFileSystemManager;")
    public native net.sf.robocode.host.io.RobotFileSystemManager getRobotFileSystemManager();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/ClassLoader;")
    public native java.lang.ClassLoader getRobotClassloader();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)V")
    public native void println(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void run();
}
//</generated-proxy>
