// ------------------------------------------------------------------------------
// <autogenerated>
// This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------------

package net.sf.robocode.host;


@net.sf.jni4net.attributes.ClrTypeInfo
public final class RobotStatics_ {
    
	// <generated-static>
	private static system.Type staticType;
    
	public static system.Type typeof() {
		return net.sf.robocode.host.RobotStatics_.staticType;
	}
    
	private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
		net.sf.robocode.host.RobotStatics_.staticType = staticType;
	}
	// </generated-static>
}
