/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.sf.robocode.java-conventions")
}

dependencies {
    implementation(project(":robocode.api"))
    implementation(project(":robocode.core"))
    implementation("net.sf.robocode:codesize:1.2")
    runtimeOnly(project(":robocode.battle"))
}

description = "Roborumble Client"
